# Generated by Django 4.2.4 on 2023-08-09 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='end_data',
            new_name='end_date',
        ),
    ]
