# Generated by Django 4.2.4 on 2023-09-10 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_alter_customuser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deptartment', to='taskmanager.department'),
        ),
    ]
