# Generated by Django 4.2.4 on 2023-09-10 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0005_rename_tasks_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskmanager.department'),
        ),
    ]
