# Generated by Django 4.2.4 on 2023-09-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0008_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='data_sent',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
